# Generated by Django 5.0.4 on 2024-10-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=9)),
                ('quarter_1', models.FloatField()),
                ('quarter_2', models.FloatField()),
                ('quarter_3', models.FloatField()),
                ('quarter_4', models.FloatField()),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='base.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='base.subject')),
            ],
        ),
    ]
