# Generated by Django 5.0.4 on 2024-10-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
