# Generated by Django 5.0.4 on 2024-10-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_reminder_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
